#ifndef LLVM_LIB_ANALYSIS_TAINT_KNOWN_FUNCTIONS_CONFIG_H
#define LLVM_LIB_ANALYSIS_TAINT_KNOWN_FUNCTIONS_CONFIG_H

#include <stdlib.h>

static const std::string PMAllocators[] = {
	//libpmem
    "pmem_map_file",
	//pmdk/common
	"util_map_sync"
}; 


static const std::string PMAllocatorsArg7Lv1[] =  {
	//libpmem2
	"file_map",
};

static const std::string noAliasFunctions[] = {
	//libc functions
	"abort",
	"__cxa_begin_catch", 
	"dup",
	"gnu_dev_major",
	"gnu_dev_minor",
	"rand",
	//Linux standard base functions
	"dlopen",
	"dlclose",
	"dlerror",
	"dlsym",
	"fts_close",
	"fts_open",
	"fts_read",
	"madvise",
	"mprotect",
	"posix_fallocate",
	"sched_yield",
	"secure_getenv",
	"secure_setenv",
	"sysconf",
	"__errno_location",
	"__ctype_b_loc",
	"__xpg_strerror_r",
	//std functions
	"_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc", //std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)
	"_ZNSolsEPFRSoS_E", //std::ostream::operator<<(std::ostream& (*)(std::ostream&)),
	"_ZStanSt12memory_orderSt23__memory_order_modifier", //std::operator&(std::memory_order, std::__memory_order_modifier)
	"_ZNSt6chrono3_V212system_clock3nowEv", //std::chrono::_V2::system_clock::now()
	"_ZNSt6thread2idC2Ev", //std::thread::id::id()
	"_ZNSt6thread6_StateC2Ev", //std::thread::_State::_State()
	"_ZNSt6threadD2Ev", //std::thread::~thread()
	"_ZSt9terminatev", //std::terminate()
	"_ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE", //std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())
	"_ZSt20__throw_length_errorPKc", //std::__throw_length_error(char const*)
	"_ZSt17__throw_bad_allocv", //std::__throw_bad_alloc()
	"_ZNSt6thread4joinEv", //std::thread::join()
	"__assert_fail",
	//posix functions
	"accept",
	"access",
	"adjtime",
	"bind",
	"chdir",
	"chflags",
	"chmod",
	"chown",
	"chroot",
	"close",
	"connect",
	"dup",
	"dup2",
	"fchdir",
	"fchflags",
	"fchmod",
	"fchown",
	"fcntl",
	"flock",
	"fpathconf",
	"fstat",
	"fstatfs",
	"fsync",
	"ftruncate",
	"getdirentries",
	"getdomainname",
	"getegid",
	"geteuid",
	"getfh",
	"getfsstat",
	"getgid",
	"gethostname",
	"getpeername",
	"getpgid",
	"getpgrp",
	"getpid",
	"getppid",
	"getrlimit",
	"getsid",
	"getsockname",
	"getsockopt",
	"gettimeofday",
	"getuid",
	"hostname",
	"ioctl",
	"issetugid",
	"kill",
	"link",
	"listen",
	"lseek",
	"lstat",
	"mkdir",
	"mkfifo",
	"mknod",
	"mmap",
	"mount",
	"mq_close",
	"mq_getattr",
	"mq_open",
	"mq_receive",
	"mq_send",
	"mq_setattr",
	"mq_unlink",
	"munmap",
	"nfssvc",
	"nvramapi",
	"open",
	"pathconf",
	"pipe",
	"poll",
	"posix_spawn",
	"posix_spawnp",
	"read",
	"readlink",
	"readv",
	"recv",
	"recvfrom",
	"recvmsg",
	"rename",
	"rmdir",
	"select",
	"send",
	"sendmsg",
	"sendto",
	"setdomainname",
	"setegid",
	"seteuid",
	"setgid",
	"sethostname",
	"setpgid",
	"setpgrp",
	"setrlimit",
	"setsid",
	"setsockopt",
	"settimeofday",
	"setuid",
	"shm_open",
	"shm_unlink",
	"shutdown",
	"sigaction",
	"sigpending",
	"sigprocmask",
	"sigqueue",
	"sigsuspend",
	"sigtimedwait",
	"sigwait",
	"sigwaitinfo",
	"socket",
	"socketpair",
	"stat",
	"statfs",
	"swapon",
	"symlink",
	"sync",
	"truncate",
	"umask",
	"unlink",
	"unmount",
	"utimes",
	"wait",
	"write",
	"writev",
	//posix thread functions
	"pthread_once",
	"pthread_getspecific",
	"pthread_key_create",
	"pthread_key_delete",
	"pthread_mutex_lock",
	"pthread_mutex_unlock",
	"pthread_mutex_init",
	"pthread_mutex_destroy",
	"pthread_rwlock_destroy",
	"pthread_cond_destrory",
	//temporary 
	//"_Malloc",
};
#endif //LLVM_LIB_ANALYSIS_TAINT_KNOWN_FUNCTIONS_CONFIG_H
